### ISSUE TITLE
Vision Java Port

### ISSUE THREAD

**Issue by joecaraccio** [Team138Entropy/Entropy2021#22]
Port the Vision System to Java

- [ ] Generate a Java Project (with Gradle)

- [ ] Add OpenCV as a dependency 

- [ ] Utilizing Thread, have 2 Camera Threads (High Goal and Ball Camera) send information to a thread safe queues. 2 Processing threads then perform algorithms and extract targets coordinates (some sort of Java class would do, you could use our Target Information class in the main robot code as a dependency)

- [ ] Add Target Coordinate classes to a final processing queue which the last Thread (the sender) will take out of the queue, convert to json, and send to the robot

^Above is a rough high level idea of how this system would work. In order to be fast we need to use multiple threads, and ensure we have thread safety across each one. 2 Camera Threads, 2 Processing Threads, and 1 Output Thread.

It might make sense to use a common class "Algorithm" and require our algorithms to subclass that class. That class could have a "sendFrame()"  function which the camera threads will send the 2d array frame information to be processed

Examples of how to interact with the cameras can be found in this java project: 
https://github.com/wpilibsuite/FRCVision-pi-gen/releases

**Comment by maxh65000** [comment]
@averwhy @joecaraccio 
Before we do this, I think we should check how much time it takes to process a single frame; if it takes 5ms per frame then I don't think there's much to be gained. But if we're spending 500ms waiting for a single frame to be turned into numbers, then this would make sense. Also, isn't much (if not all) of the heavy lifting done in OpenCV and therefore already optimized C++?

**Comment by joecaraccio** [comment]
@maxh65000 so I think we measured it before and we process each frame over 100 times lol. I doubt there would be a speed improvement with opencv (you are right that it's all just calling C code anyways).

Where I really care is the concurrency. Currently If you look in python we use threads and a thread safe queue to send back our data. We could also do something with the multiprocessing module, but if we're just going to use threads, java would be a better solution.

**Comment by joecaraccio** [comment]
@averwhy 

You are going to want to flash a SD Card to boot this image: 
https://github.com/wpilibsuite/FRCVision-pi-gen/releases

Thats the flavor that we are currently running. I think you've seen it before but it has a nice web dashboard.

Another thing to consider is if we want to learn how to split the camera feed coming in from the robot  (to allow us to Vision Sample and use that same camera as driver feedback). This could help in two cases:

- Weight - (if its really tight). Not long ago we put our robot on the scale and it said 120 pounds exactly
- Position - shooter would be an example...can't really get two cameras centered on that thing

**Comment by averwhy** [comment]
joe read discord
